import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ProfileForm from '../component/ProfileForm'
import Drive from '../component/ShadowDrive'
import styles from '../styles/Home.module.css'
import { Text } from "@nextui-org/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shadow Drive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ProfileForm />
      </main>

      <footer className={styles.footer}>
        <Text h5 color='white'> Made with ❤️ by Vijay </Text>
      </footer>
    </div>
  )
}

export default Home
